# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31b33be20ba5bb8bc64507518f6c7fb7810e87b1ff88822a06086d2e6988b4bfa861b641d19127a127bd183e6dede8075c56e1c933b87f994ea56395e0e5b80a

test:
  secret_key_base: 52fb02f883927b389d2109d65f4ca1098cebcff91a55b6d0e1ea56b53be5c54f4a46a46109758f83fbea897d95cba7d58c4eb0e8a1333ab12b827ec8df382c77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
